pub mod adapters;
pub mod cursor;
mod display_capture;
pub mod events;
pub mod input;
pub mod layout;
mod local_presentation;
pub mod prompt_ui;
pub mod provider;
pub mod render;
pub mod runtime;
pub mod scrollback_cache;
pub mod scrollback_fetch;
mod scrollback_modes;
pub mod sim;
pub mod state;
mod tui_surface;
