//! Typed public API of the bmux decoration plugin.
//!
//! See `bpdl/decoration-plugin.bpdl` for the full schema. The
//! [`decoration_state`] module is generated by the
//! [`bmux_plugin_schema_macros::schema!`] proc-macro and contains all
//! records, variants, enums, and the `DecorationStateService` trait.

#![cfg_attr(feature = "fail-on-warnings", deny(warnings))]
#![warn(clippy::all, clippy::pedantic)]
#![allow(clippy::module_name_repetitions)]

bmux_plugin_schema_macros::schema! {
    source: "bpdl/decoration-plugin.bpdl",
    imports: {
        scene: {
            source: "../../packages/scene-protocol/bpdl/scene-protocol.bpdl",
            crate_path: ::bmux_scene_protocol,
        },
    },
}
