//! Types and trait for bmux configuration documentation schema.
//!
//! This crate defines the `ConfigDocSchema` trait and `FieldDoc` type that are
//! implemented by the `#[derive(ConfigDoc)]` proc macro. The docs site uses
//! these to generate the configuration reference page.

use std::collections::BTreeMap;

/// Metadata for a single configuration field.
pub struct FieldDoc {
    /// TOML key name for this field.
    pub toml_key: &'static str,
    /// Human-readable type name (e.g. "bool", "string", "integer").
    pub type_display: &'static str,
    /// Description extracted from the field's `///` doc comment.
    pub description: &'static str,
    /// For enum-typed fields, the list of valid TOML values.
    pub enum_values: Option<&'static [&'static str]>,
}

/// Trait implemented by config structs via `#[derive(ConfigDoc)]`.
///
/// Provides all metadata needed to generate a configuration reference.
pub trait ConfigDocSchema: Default {
    /// TOML section name (e.g. `"general"`, `"behavior"`).
    fn section_name() -> &'static str;

    /// Section description extracted from the struct's doc comment.
    fn section_description() -> &'static str;

    /// Metadata for each field in this config section.
    fn field_docs() -> Vec<FieldDoc>;

    /// Default values for each field, serialized as TOML strings.
    ///
    /// Keys are TOML field names, values are the serialized default.
    /// Generated by constructing `Self::default()` and serializing each field.
    fn default_values() -> BTreeMap<String, String>;
}
