[keybindings.modes.insert.bindings]
"ctrl+a %"     = "split_focused_vertical"
"ctrl+a &"     = "plugin:bmux.windows:close-current-window"
"ctrl+a ["     = "enter_scroll_mode"
"ctrl+a \""    = "split_focused_horizontal"
"ctrl+a ^"     = "plugin:bmux.windows:last-window"
"ctrl+a c"     = "plugin:bmux.windows:new-window"
"ctrl+a d"     = "detach"
"ctrl+a down"  = "focus_down_pane"
"ctrl+a h"     = "focus_left_pane"
"ctrl+a j"     = "focus_down_pane"
"ctrl+a k"     = "focus_up_pane"
"ctrl+a l"     = "focus_right_pane"
"ctrl+a left"  = "focus_left_pane"
"ctrl+a n"     = "plugin:bmux.windows:next-window"
"ctrl+a o"     = "focus_next_pane"
"ctrl+a p"     = "plugin:bmux.windows:prev-window"
"ctrl+a right" = "focus_right_pane"
"ctrl+a up"    = "focus_up_pane"
"ctrl+a z"     = "zoom_pane"

[keybindings.global]
"alt+h" = "focus_left_pane"
"alt+j" = "focus_down_pane"
"alt+k" = "focus_up_pane"
"alt+l" = "focus_right_pane"
"alt+n" = "split_focused_horizontal"
"alt+v" = "split_focused_vertical"
"alt+x" = "plugin:bmux.windows:close-active-pane"
"alt+z" = "zoom_pane"
