#![cfg_attr(feature = "fail-on-warnings", deny(warnings))]
#![warn(clippy::all, clippy::pedantic, clippy::nursery, clippy::cargo)]
#![allow(clippy::multiple_crate_versions)]
#![allow(clippy::cargo_common_metadata)]

use anyhow::{Result, bail};

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RuntimeAction {
    Quit,
    Detach,
    NewWindow,
    NewSession,
    SessionPrev,
    SessionNext,
    FocusNext,
    FocusLeft,
    FocusRight,
    FocusUp,
    FocusDown,
    ToggleSplitDirection,
    SplitFocusedVertical,
    SplitFocusedHorizontal,
    IncreaseSplit,
    DecreaseSplit,
    ResizeLeft,
    ResizeRight,
    ResizeUp,
    ResizeDown,
    RestartFocusedPane,
    CloseFocusedPane,
    ShowHelp,
    EnterScrollMode,
    ExitScrollMode,
    ScrollUpLine,
    ScrollDownLine,
    ScrollUpPage,
    ScrollDownPage,
    ScrollTop,
    ScrollBottom,
    BeginSelection,
    MoveCursorLeft,
    MoveCursorRight,
    MoveCursorUp,
    MoveCursorDown,
    CopyScrollback,
    ConfirmScrollback,
    EnterWindowMode,
    ExitMode,
    WindowPrev,
    WindowNext,
    WindowGoto1,
    WindowGoto2,
    WindowGoto3,
    WindowGoto4,
    WindowGoto5,
    WindowGoto6,
    WindowGoto7,
    WindowGoto8,
    WindowGoto9,
    WindowClose,
    ForwardToPane(Vec<u8>),
}

pub const fn action_to_name(action: &RuntimeAction) -> &'static str {
    match action {
        RuntimeAction::Quit => "quit",
        RuntimeAction::Detach => "detach",
        RuntimeAction::NewWindow => "new_window",
        RuntimeAction::NewSession => "new_session",
        RuntimeAction::SessionPrev => "session_prev",
        RuntimeAction::SessionNext => "session_next",
        RuntimeAction::FocusNext => "focus_next_pane",
        RuntimeAction::FocusLeft => "focus_left_pane",
        RuntimeAction::FocusRight => "focus_right_pane",
        RuntimeAction::FocusUp => "focus_up_pane",
        RuntimeAction::FocusDown => "focus_down_pane",
        RuntimeAction::ToggleSplitDirection => "toggle_split_direction",
        RuntimeAction::SplitFocusedVertical => "split_focused_vertical",
        RuntimeAction::SplitFocusedHorizontal => "split_focused_horizontal",
        RuntimeAction::IncreaseSplit => "increase_split",
        RuntimeAction::DecreaseSplit => "decrease_split",
        RuntimeAction::ResizeLeft => "resize_left",
        RuntimeAction::ResizeRight => "resize_right",
        RuntimeAction::ResizeUp => "resize_up",
        RuntimeAction::ResizeDown => "resize_down",
        RuntimeAction::RestartFocusedPane => "restart_focused_pane",
        RuntimeAction::CloseFocusedPane => "close_focused_pane",
        RuntimeAction::ShowHelp => "show_help",
        RuntimeAction::EnterScrollMode => "enter_scroll_mode",
        RuntimeAction::ExitScrollMode => "exit_scroll_mode",
        RuntimeAction::ScrollUpLine => "scroll_up_line",
        RuntimeAction::ScrollDownLine => "scroll_down_line",
        RuntimeAction::ScrollUpPage => "scroll_up_page",
        RuntimeAction::ScrollDownPage => "scroll_down_page",
        RuntimeAction::ScrollTop => "scroll_top",
        RuntimeAction::ScrollBottom => "scroll_bottom",
        RuntimeAction::BeginSelection => "begin_selection",
        RuntimeAction::MoveCursorLeft => "move_cursor_left",
        RuntimeAction::MoveCursorRight => "move_cursor_right",
        RuntimeAction::MoveCursorUp => "move_cursor_up",
        RuntimeAction::MoveCursorDown => "move_cursor_down",
        RuntimeAction::CopyScrollback => "copy_scrollback",
        RuntimeAction::ConfirmScrollback => "confirm_scrollback",
        RuntimeAction::EnterWindowMode => "enter_window_mode",
        RuntimeAction::ExitMode => "exit_mode",
        RuntimeAction::WindowPrev => "window_prev",
        RuntimeAction::WindowNext => "window_next",
        RuntimeAction::WindowGoto1 => "window_goto_1",
        RuntimeAction::WindowGoto2 => "window_goto_2",
        RuntimeAction::WindowGoto3 => "window_goto_3",
        RuntimeAction::WindowGoto4 => "window_goto_4",
        RuntimeAction::WindowGoto5 => "window_goto_5",
        RuntimeAction::WindowGoto6 => "window_goto_6",
        RuntimeAction::WindowGoto7 => "window_goto_7",
        RuntimeAction::WindowGoto8 => "window_goto_8",
        RuntimeAction::WindowGoto9 => "window_goto_9",
        RuntimeAction::WindowClose => "window_close",
        RuntimeAction::ForwardToPane(_) => "forward_to_pane",
    }
}

pub fn parse_action(value: &str) -> Result<RuntimeAction> {
    match value {
        "quit" => Ok(RuntimeAction::Quit),
        "detach" => Ok(RuntimeAction::Detach),
        "new_window" => Ok(RuntimeAction::NewWindow),
        "new_session" => Ok(RuntimeAction::NewSession),
        "session_prev" => Ok(RuntimeAction::SessionPrev),
        "session_next" => Ok(RuntimeAction::SessionNext),
        "focus_next_pane" => Ok(RuntimeAction::FocusNext),
        "focus_left_pane" => Ok(RuntimeAction::FocusLeft),
        "focus_right_pane" => Ok(RuntimeAction::FocusRight),
        "focus_up_pane" => Ok(RuntimeAction::FocusUp),
        "focus_down_pane" => Ok(RuntimeAction::FocusDown),
        "toggle_split_direction" => Ok(RuntimeAction::ToggleSplitDirection),
        "split_focused_vertical" => Ok(RuntimeAction::SplitFocusedVertical),
        "split_focused_horizontal" => Ok(RuntimeAction::SplitFocusedHorizontal),
        "increase_split" => Ok(RuntimeAction::IncreaseSplit),
        "decrease_split" => Ok(RuntimeAction::DecreaseSplit),
        "resize_left" => Ok(RuntimeAction::ResizeLeft),
        "resize_right" => Ok(RuntimeAction::ResizeRight),
        "resize_up" => Ok(RuntimeAction::ResizeUp),
        "resize_down" => Ok(RuntimeAction::ResizeDown),
        "restart_focused_pane" => Ok(RuntimeAction::RestartFocusedPane),
        "close_focused_pane" => Ok(RuntimeAction::CloseFocusedPane),
        "show_help" => Ok(RuntimeAction::ShowHelp),
        "enter_scroll_mode" => Ok(RuntimeAction::EnterScrollMode),
        "exit_scroll_mode" => Ok(RuntimeAction::ExitScrollMode),
        "scroll_up_line" => Ok(RuntimeAction::ScrollUpLine),
        "scroll_down_line" => Ok(RuntimeAction::ScrollDownLine),
        "scroll_up_page" => Ok(RuntimeAction::ScrollUpPage),
        "scroll_down_page" => Ok(RuntimeAction::ScrollDownPage),
        "scroll_top" => Ok(RuntimeAction::ScrollTop),
        "scroll_bottom" => Ok(RuntimeAction::ScrollBottom),
        "begin_selection" => Ok(RuntimeAction::BeginSelection),
        "move_cursor_left" => Ok(RuntimeAction::MoveCursorLeft),
        "move_cursor_right" => Ok(RuntimeAction::MoveCursorRight),
        "move_cursor_up" => Ok(RuntimeAction::MoveCursorUp),
        "move_cursor_down" => Ok(RuntimeAction::MoveCursorDown),
        "copy_scrollback" => Ok(RuntimeAction::CopyScrollback),
        "confirm_scrollback" => Ok(RuntimeAction::ConfirmScrollback),
        "enter_window_mode" => Ok(RuntimeAction::EnterWindowMode),
        "exit_mode" => Ok(RuntimeAction::ExitMode),
        "window_prev" => Ok(RuntimeAction::WindowPrev),
        "window_next" => Ok(RuntimeAction::WindowNext),
        "window_goto_1" => Ok(RuntimeAction::WindowGoto1),
        "window_goto_2" => Ok(RuntimeAction::WindowGoto2),
        "window_goto_3" => Ok(RuntimeAction::WindowGoto3),
        "window_goto_4" => Ok(RuntimeAction::WindowGoto4),
        "window_goto_5" => Ok(RuntimeAction::WindowGoto5),
        "window_goto_6" => Ok(RuntimeAction::WindowGoto6),
        "window_goto_7" => Ok(RuntimeAction::WindowGoto7),
        "window_goto_8" => Ok(RuntimeAction::WindowGoto8),
        "window_goto_9" => Ok(RuntimeAction::WindowGoto9),
        "window_close" => Ok(RuntimeAction::WindowClose),
        unknown => bail!("unknown keymap action '{unknown}'"),
    }
}
