//! Typed scene-decoration protocol.
//!
//! Plugins that paint chrome around pane surfaces (borders, badges,
//! focus highlights) publish a [`scene_protocol::DecorationScene`] on
//! the typed plugin event bus. Core caches the latest snapshot and
//! consults it during frame assembly to determine each surface's
//! authoritative `content_rect` and any paint commands to apply.
//!
//! See `bpdl/scene-protocol.bpdl` for the full schema. The
//! [`scene_protocol`] module is generated by the
//! [`bmux_plugin_schema_macros::schema!`] proc macro.

#![cfg_attr(feature = "fail-on-warnings", deny(warnings))]
#![warn(clippy::all, clippy::pedantic)]
#![allow(clippy::module_name_repetitions)]

bmux_plugin_schema_macros::schema! {
    source: "bpdl/scene-protocol.bpdl",
}
