[package]
authors     = { workspace = true }
categories  = ["command-line-interface", "gui"]
description = "Gallery examples for bmux_tui_components"
edition     = { workspace = true }
keywords    = ["bmux", "example", "tui", "components"]
license     = { workspace = true }
name        = "bmux_tui_components_gallery"
publish     = false
readme      = "README.md"
repository  = { workspace = true }
version     = { workspace = true }

[dependencies]
anyhow              = { workspace = true, features = ["std"] }
bmux_keyboard       = { workspace = true }
bmux_text_edit      = { workspace = true }
bmux_tui            = { workspace = true, features = ["crossterm"] }
bmux_tui_components = { workspace = true, features = ["text-input"] }
bmux_tui_runtime    = { workspace = true, features = ["crossterm"] }
tokio               = { workspace = true, features = ["macros", "rt"] }

[features]
fail-on-warnings = ["bmux_tui_components/fail-on-warnings"]
