[package]
authors     = { workspace = true }
categories  = ["development-tools"]
description = "Bundled horizontal window presentation plugin for bmux"
edition     = { workspace = true }
keywords    = ["bmux", "plugin", "tabs"]
license     = { workspace = true }
name        = "bmux_tab_strip_plugin"
repository  = { workspace = true }
version     = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bmux_attach_view_protocol = { workspace = true }
bmux_plugin               = { workspace = true }
bmux_plugin_sdk           = { workspace = true }
bmux_presentation_state   = { workspace = true }
bmux_text_edit            = { workspace = true }
bmux_windows_plugin_api   = { workspace = true }
serde                     = { workspace = true }
tokio                     = { workspace = true, features = ["rt", "sync"] }
toml                      = { workspace = true }
tracing                   = { workspace = true }
unicode-segmentation      = { workspace = true }
unicode-width             = { workspace = true }
uuid                      = { workspace = true, features = ["std"] }

[features]
fail-on-warnings = [
    "bmux_attach_view_protocol/fail-on-warnings",
    "bmux_plugin/fail-on-warnings",
    "bmux_plugin_sdk/fail-on-warnings",
    "bmux_presentation_state/fail-on-warnings",
    "bmux_windows_plugin_api/fail-on-warnings",
]
static-bundled = []
