[package]
authors     = { workspace = true }
categories  = ["command-line-interface", "gui"]
description = "Layout playground examples for bmux_tui_components"
edition     = { workspace = true }
keywords    = ["bmux", "example", "tui", "layout"]
license     = { workspace = true }
name        = "bmux_tui_components_layout_playground"
publish     = false
readme      = "README.md"
repository  = { workspace = true }
version     = { workspace = true }

[dependencies]
anyhow = { workspace = true, features = ["std"] }
bmux_keyboard = { workspace = true }
bmux_tui = { workspace = true, features = ["crossterm"] }
bmux_tui_components = { workspace = true, features = [
    "modal-frame",
    "pane",
    "panel-group",
] }

[features]
fail-on-warnings = ["bmux_tui_components/fail-on-warnings"]
